# Generated by Django 4.1.3 on 2022-11-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("status", models.BooleanField(default=False)),
                ("pdf", models.FileField(upload_to="unTransFile/")),
            ],
        ),
    ]
