# Generated by Django 4.1.3 on 2022-11-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file", name="pdf", field=models.FileField(upload_to=""),
        ),
    ]
