# Generated by Django 4.1.3 on 2022-11-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_file_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="pdf",
            field=models.FileField(upload_to="unTransFile/"),
        ),
    ]
